# Leka - iOS Monorepo
# Copyright 2023 APF France handicap
# SPDX-License-Identifier: Apache-2.0

name: Linter - Swift Format

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  swift_format:
    name: lint
    runs-on: [self-hosted, iOS]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags
          lfs: true

      - name: Run swift-format
        run: |
          echo ""
          echo "üèÉ‚Äç‚ôÇÔ∏è Running swift-format on modified files ü§µ‚Äç‚ôÇÔ∏è"

          git diff --name-status origin/main          \
            | grep -E "^A|^M" | sed "s/^[AM]\t//g"    \
            | grep -E "\.swift\$$"                    \
            || echo "No files added nor modified!"

          git diff --name-status origin/main          \
            | grep -E "^A|^M" | sed "s/^[AM]\t//g"    \
            | grep -E "\.swift\$$"                    \
            | xargs --no-run-if-empty swift-format lint --strict --color-diagnostics --parallel
